### ISSUE TITLE
Notice: Undefined index: HTTP_X_CLASSMARKER_HMAC_SHA256

### ISSUE THREAD

**Issue by PK1NONLY** [classmarker/retrieve-quiz-results-webhooks-php#1]
the below line was giveing  err as : $header_hmac_signature =$_SERVER['HTTP_X_CLASSMARKER_HMAC_SHA256'] 

which got fixed by changing the same line to Notice: Undefined index: 
$header_hmac_signature = isset($_SERVER['HTTP_X_CLASSMARKER_HMAC_SHA256']);

 but still i am getting 400 err please help me out here

**Comment by PK1NONLY** [comment]
**see my codes below:** 
`<?php
// PHP webhooks code example by ClassMarker.com


// You are given a uniquе secret codе when creating a Wеbhook.
define('CLASSMARKER_WEBHOOK_SECRET', 'my key');

// Verification function.
function verify_classmarker_webhook($json_data, $header_hmac_signature)
{

	$calculated_signature = base64_encode(hash_hmac('sha256', $json_data, CLASSMARKER_WEBHOOK_SECRET, true));
	return ($header_hmac_signature == $calculated_signature);

}


// ClassMarker sent signaturе to chеck against.

$header_hmac_signature = isset($_SERVER['HTTP_X_CLASSMARKER_HMAC_SHA256']);

// ClassMarker JSON payload (The Tеst Results).
$json_string_payload = file_get_contents('php://input');

// Call vеrification function.
$verified = verify_classmarker_webhook($json_string_payload, $header_hmac_signature);

// Add JSON payload to array for rеferencing elements.

$array_payload = json_decode($json_string_payload, true);

if ($verified)
{
	echo $array_payload;

	// Notify ClassMarker you have recеived the Wеbhook.
	http_response_code(200);
		echo "200";
	// Save results in your databasе.
	// Important: Do not use a script that will takе a long time to respond.

} else  {

echo "400";
	// Something went wrong.
	http_response_code(400);

}




`

**Comment by eltreno** [comment]
Hi,

The line below is correct, you should not change it.
$header_hmac_signature = $_SERVER['HTTP_X_CLASSMARKER_HMAC_SHA256'];

It looks like you are browsing to the script yourself, which you cannot do, webhooks scripts like this are written to only accept data from other websites.

Instead of **echo $array_payload;** in your code, try to write **$json_string_payload to a log file**, so you can see the request coming from ClassMarker, then you can start to work on adding the Payload Test results to your database.
